# Generated by Django 3.2.10 on 2022-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='transport',
            field=models.ManyToManyField(related_name='journey', to='bus.Transport'),
        ),
    ]
