# Generated by Django 3.2.10 on 2022-07-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_journey_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='bus_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_category', to='bus.category'),
        ),
    ]
